#!/usr/bin/env python

Import('env')

from compat import open_utf8
from distutils.version import LooseVersion
from detect import get_ndk_version

env_module = env.Clone()

# Thirdparty source files

thirdparty_dir = 'thirdparty/'

pjlib_dir = thirdparty_dir + 'pjlib/src/pj/'

# pjlib_util_dir = 'thirdparty/pjlib-util/'
# pjlib_util_dirs = [
#     pjlib_util_dir + 'src/pjlib-util/',
# ]

# pjnath_dir = 'thirdparty/pjnath/'
# pjnath_dirs = [
#     pjnath_dir + 'src/pjnath/',
# ]

env_module.Prepend(CPPPATH=[thirdparty_dir + 'pjlib/include/'])
# env_module.Prepend(CPPPATH=[pjlib_util_dir + 'include/'])
# env_module.Prepend(CPPPATH=[pjnath_dir + 'include/'])

env_thirdparty = env_module.Clone()

# Common sources
pjlib_sources = [
    
    # Common sources
    'activesock.c',
    'addr_resolv_sock.c',
    'array.c',
    'config.c',
    'ctype.c',
    'errno.c',
    'except.c',
    'fifobuf.c',
    'file_io_ansi.c',
    'ioqueue_select.c',
    'ip_helper_generic.c',
    'list.c',
    'log.c',
    'hash.c',
    'ioqueue_epoll.c',
    'lock.c',
    'os_timestamp_common.c',
    'os_time_common.c',
    'log_writer_stdout.c',
    'os_info.c',
    'os_timestamp_posix.c',
    'pool_policy_malloc.c',
    'rand.c',
    'pool.c',
    'rbtree.c',
    'pool_buf.c',
    'pool_policy_new.cpp',
    'sock_common.c',
    'sock_qos_common.c',
    'sock_qos_dummy.c',
    'sock_select.c',
    'pool_caching.c',
    'pool_dbg.c',
    'ssl_sock_common.c',
    'ssl_sock_dump.c',
    'ssl_sock_ossl.c',
    'ssl_sock_gtls.c',
    'string.c',
    'ssl_sock_imp_common.c',
    'symbols.c',
    'types.c',
    'timer.c',
    'guid.c',
    'guid_simple.c',
    
    # 'guid_uuid.c',
    # 'pool_signature.h', TODO
    
    # Symbian sources
    
    # 'addr_resolv_symbian.cpp',
    # 'exception_symbian.cpp',
    # 'ioqueue_symbian.cpp',
    # 'ip_helper_symbian.cpp',
    # 'log_writer_symbian_console.cpp',
    # 'os_core_symbian.cpp',
    # 'os_error_symbian.cpp',
    # 'os_info_symbian.cpp',
    # 'sock_qos_symbian.cpp',
    # 'sock_select_symbian.cpp',
    # 'ssl_sock_symbian.cpp',
    # 'timer_symbian.cpp',
    # 'unicode_symbian.cpp',
    # 'os_symbian.h',
    # 'sock_symbian.cpp',
    
    # UNIX/Linux
    'file_access_unistd.c',
    'os_core_unix.c',
    'os_error_unix.c',
    'os_time_unix.c',
    
    # 'extra-exports.c'
    # 'log_writer_printk.c', # exclusively for the Linux Kernel
    # 'pool_policy_kmalloc.c',
    
    # 'os_time_bsd.c',
    # 'sock_bsd.c',
    # 'sock_qos_bsd.c',
    
    # Windows
    # 'file_access_win32.c',
    # 'file_io_win32.c',
    # 'guid_win32.c',
    # 'ioqueue_winnt.c',
    # 'ip_helper_win32.c',
    # 'os_core_win32.c',
    # 'os_error_win32.c',
    # 'os_timestamp_win32.c',
    # 'os_time_win32.c',
    # 'sock_qos_wm.c',
    # 'unicode_win32.c',
    
    # UWP
    # 'ioqueue_uwp.cpp',
    # 'ip_helper_winphone8.c',
    # 'sock_uwp.cpp',
    # 'sock_uwp.h',
    
    # MacOS
    # 'os_core_darwin.m',
    # 'sock_qos_darwin.c',
    # 'ssl_sock_darwin.c',
    # 'os_info_iphone.m',
    
    # 'ioqueue_common_abs.c', # NOT supposed to be compiled as stand-alone source
    # 'ioqueue_common_abs.h',
    # 'ioqueue_dummy.c', # no implementation
    # 'os_rwmutex.c', # THIS FILE WILL BE INCLUDED BY os_core_*.c
    # 'ssl_sock_imp_common.h',
    
    # Compat
    # 'compat/sigjmp.c',
    'compat/string_compat.c',
    # 'compat/string.c',
]

pjlib_sources = [pjlib_dir + file for file in pjlib_sources]

# Platform specific setup
if env["platform"] == "android":

    env_thirdparty.Append(CPPDEFINES={
            'PJ_M_NAME' : '\\\"' + env['android_arch'] + '\\\"',
            'PJ_IS_LITTLE_ENDIAN' : 1,
            'PJ_IS_BIG_ENDIAN' : 0,
        }
    )
    pjlib_android_sources = [
        'guid_android.c'
    ]
    pjlib_sources += [pjlib_dir + file for file in pjlib_android_sources],


env_thirdparty.add_source_files(env.modules_sources, pjlib_sources)
    
env_thirdparty.disable_warnings()

# Optional arguments
for key, value in ARGLIST:
    if key == 'define':
        env_module.Append(CPPDEFINES=[value])

# Add module sources
env_module.add_source_files(env.modules_sources, '*.cpp')

Export('env_module')
